 spring:
    datasource:     
      url: jdbc:mysql://localhost:3306/prueba?useSSL=false
      username: root
      password: root123456789
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update